### ISSUE TITLE
Issue with python 3.3 running "recorder config setup"

### ISSUE THREAD

**Issue by jamespo** [DirkR/podhorst#18]
Traceback (most recent call last):
  File "/home/james/.virtualenvs/misc3/bin/recorder", line 9, in <module>
    load_entry_point('capturadio==0.11.0', 'console_scripts', 'recorder')()
  File "/home/james/.virtualenvs/misc3/lib/python3.3/site-packages/capturadio-0.11.0-py3.3.egg/capturadio/recorder_cli.py", line 315, in main
    Configuration().write_config()
  File "/home/james/.virtualenvs/misc3/lib/python3.3/site-packages/capturadio-0.11.0-py3.3.egg/capturadio/config.py", line 106, in __init__
    self.write_config()
  File "/home/james/.virtualenvs/misc3/lib/python3.3/site-packages/capturadio-0.11.0-py3.3.egg/capturadio/config.py", line 119, in write_config
    config.set('settings', key, self.__dict__[key])
  File "/usr/lib64/python3.3/configparser.py", line 1184, in set
    super().set(section, option, value)
  File "/usr/lib64/python3.3/configparser.py", line 889, in set
    value)
  File "/usr/lib64/python3.3/configparser.py", line 399, in before_set
    "position %d" % (value, tmp_value.find('%')))
ValueError: invalid interpolation syntax in '%Y-%m-%d' at position 0

This is the version of python3 that comes with Centos/RHEL 7

**Comment by jamespo** [comment]
I also get this in 3.6.1, does it not work in a virtual env?

**Comment by rgagnon** [comment]
same here

**Comment by TarAll** [comment]
i'm getting this error too under python 3.5.2 and ubuntu 16.04

**Comment by DirkR** [comment]
Oh, sorry. This code hasn't got enough love during the py3 transition. I fixed this bug and released version 0.11.1.

I'll keep on woking to get the codebase more robust for the next major release.
