### ISSUE TITLE
recorder feed update not working

### ISSUE THREAD

**Issue by jamespo** [DirkR/podhorst#20]
Records fine for me now (thanks!) and I'm using it but the RSS generation doesn't seem to work:

(podhorst) [james@miniproj podhorst]$ recorder feed list
bbc2/bobharrissunday/bobharrissunday_2017-06-17_15-08.mp3: Episode("Bob Harris Sunday, 2017-06-17")
abs80s/forgotten80s/forgotten80s_2017-06-17_15-20.mp3: Episode("Forgotten 80s, 2017-06-17")
(podhorst) [james@miniproj podhorst]$ recorder feed update
Traceback (most recent call last):
  File "/home/james/.virtualenvs/podhorst/bin/recorder", line 11, in <module>
    load_entry_point('capturadio==0.11.1', 'console_scripts', 'recorder')()
  File "/home/james/.virtualenvs/podhorst/lib/python3.6/site-packages/capturadio-0.11.1-py3.6.egg/capturadio/recorder_cli.py", line 325, in main
    method(args)
  File "/home/james/.virtualenvs/podhorst/lib/python3.6/site-packages/capturadio-0.11.1-py3.6.egg/capturadio/recorder_cli.py", line 218, in feed_update
    generate_feed(config, db, root)
  File "/home/james/.virtualenvs/podhorst/lib/python3.6/site-packages/capturadio-0.11.1-py3.6.egg/capturadio/generator.py", line 87, in generate_feed
    contents = j2_env.get_template('feed.xml.jinja2').render(
  File "/home/james/.virtualenvs/podhorst/lib/python3.6/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/james/.virtualenvs/podhorst/lib/python3.6/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/home/james/.virtualenvs/podhorst/lib/python3.6/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
**jinja2.exceptions.TemplateNotFound: feed.xml.jinja2**

**Comment by DirkR** [comment]
It took some time to fix it, but now it should work.
The folder "capturadio/templates/" containing the jinja2 template files wasn't listed in setup.py.
I added these files and the "feed update" command should work by now (see bf01660).
