### ISSUE TITLE
Handle exception correctly, when image could not be fetched

### ISSUE THREAD

**Issue by DirkR** [DirkR/podhorst#8]
I just got this exception, it should be handled better:

```
Traceback (most recent call last):
 File "/package/host/localhost/python-2.7/lib/python2.7/logging/__init__.py", line 846, in emit
   msg = self.format(record)
 File "/package/host/localhost/python-2.7/lib/python2.7/logging/__init__.py", line 723, in format
   return fmt.format(record)
 File "/package/host/localhost/python-2.7/lib/python2.7/logging/__init__.py", line 464, in format
   record.message = record.getMessage()
 File "/package/host/localhost/python-2.7/lib/python2.7/logging/__init__.py", line 328, in getMessage
   msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file __init__.py, line 388
Error during capturing http://a1.mzstatic.com/......jpg HTTP Error 404: Not Found
```

**Comment by DirkR** [comment]
This has been fixed meanwhile.
