### ISSUE TITLE
Catch "Connection timed out" while capturing a stream

### ISSUE THREAD

**Issue by DirkR** [DirkR/podhorst#9]
This exception should be catched and logged:

```
Traceback (most recent call last):
 File "/home/dirkr/capturadio/recorder.py", line 72, in <module>
   recorder.capture(show)
 File "/home/dirkr/capturadio/capturadio/__init__.py", line 294, in capture
   raise e
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>
```

**Comment by DirkR** [comment]
This has been fixed meanwhile.
